### ISSUE TITLE
not working w/ iOS 8 and OS X  10.10

### ISSUE THREAD

**Issue by MoritzFago** [mdlayher/amiusingmptcp#4] opened 2015-06-08 18:22 UTC
see title

**Comment by mdlayher** [comment] 2015-06-08 18:53
I suspect I know what the problem is.  Will report back once it's fixed.

**Comment by mdlayher** [comment] 2015-06-08 19:01
Should be fixed now.  The VM it runs on rebooted into a non-MPTCP kernel.  I've isolated the site on its own VM so this should no longer be an issue.

**Closed by mdlayher** 2015-06-08 19:01 UTC
